#include "../thirdparty/nob.c"
#include "../thirdparty/flag.c"
#include "../thirdparty/arena.c"

#include "main.c"
#include "lexer.c"
#include "parser.c"
#include "AST.c"
#include "ir.c"
#include "compiler.c"
#include "VM.c"
#include "value.c"
#include "token.c"
#include "chunk.c"
#include "table.c"
#include "object.c"